Indicorp
Vailery/FE63-TMS pull request #1
Opened 2021-08-16 13:50 UTC by Vailery

1. [Indicorp](https://vailery.github.io/FE63-TMS/Indicorp/)

2. Preview:
![img](...)

3. Description:
- First lesson of working with layout

2021-08-24 10:34 UTC, vadiminsk requested changes

2021-08-24 10:34 UTC, vadiminsk commented on Indicorp/index.html
> +                    <ul>
Тут лучше заголовок вынести из ul,и обернуть это в див. А то заголовок как будто пункт списка

2021-08-24 10:34 UTC, vadiminsk commented on Indicorp/index.html
> +                            <h6>georgia.young@example.com</h6>
это ссылки

2021-08-24 10:34 UTC, vadiminsk commented on Indicorp/index.html
> +                        <label for="email"><h3>Subscribe For Latest Newsletter</h3></label>
Error: Element h3 not allowed as child of element label in this context. (Suppressing further errors from this subtree.)

2021-08-26 20:35 UTC, Vailery commented on Indicorp/index.html
> +                        <label for="email"><h3>Subscribe For Latest Newsletter</h3></label>
remove h3

2021-08-26 20:35 UTC, Vailery commented on Indicorp/index.html
> +                            <h6>georgia.young@example.com</h6>
change it into links

2021-08-26 20:36 UTC, Vailery commented on Indicorp/index.html
> +                    <ul>
change

2021-08-31 16:01 UTC, vadiminsk approved these changes

2021-08-31 16:01 UTC, merged